/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Surfaces
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#17648d",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#40484e",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        // Primary
        primary: "#17648d",
        "on-primary": "#ffffff",
        "primary-container": "#76b6e3",
        "on-primary-container": "#004768",
        "primary-fixed": "#c9e6ff",
        "primary-fixed-dim": "#8ecefc",
        "on-primary-fixed": "#001e2f",
        "on-primary-fixed-variant": "#004c6e",
        "inverse-primary": "#8ecefc",
        // Secondary
        secondary: "#8a486f",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffaeda",
        "on-secondary-container": "#7c3d63",
        "secondary-fixed": "#ffd8ea",
        "secondary-fixed-dim": "#ffaeda",
        "on-secondary-fixed": "#3a0329",
        "on-secondary-fixed-variant": "#6f3157",
        // Tertiary
        tertiary: "#576065",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a7b0b6",
        "on-tertiary-container": "#3a4348",
        "tertiary-fixed": "#dbe4ea",
        "tertiary-fixed-dim": "#bfc8ce",
        "on-tertiary-fixed": "#141d21",
        "on-tertiary-fixed-variant": "#3f484d",
        // Error
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        // Outline
        outline: "#71787f",
        "outline-variant": "#c0c7cf",
      },
      fontFamily: {
        "headline-xl": ["Quicksand"],
        "headline-lg": ["Quicksand"],
        "headline-lg-mobile": ["Quicksand"],
        "headline-md": ["Quicksand"],
        "headline-sm": ["Quicksand"],
        "body-lg": ["Nunito Sans"],
        "body-md": ["Nunito Sans"],
        "body-sm": ["Nunito Sans"],
        "label-md": ["Nunito Sans"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
}