// src/components/reports/ReportShell.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import '../../styles/report-print.css';

export default function ReportShell({ title, subtitle, baby, children }) {
  const generatedOn = new Date().toLocaleString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });

  return (
    <div className="report-page">
      {/* Screen-only back link */}
      <div className="no-print" style={{ maxWidth: 900, margin: '0 auto 16px' }}>
        <Link
          to={baby ? `/baby/${baby.id}` : '/babies'}
          className="inline-flex items-center gap-2 text-primary font-label-md text-label-md hover:opacity-80"
        >
          <span className="material-symbols-outlined">arrow_back</span>
          Back to {baby?.name ? `${baby.name}'s profile` : 'Babies'}
        </Link>
        <button
          onClick={() => window.print()}
          className="ml-3 inline-flex items-center gap-2 bg-primary text-on-primary px-5 py-2 rounded-full font-label-md text-label-md hover:opacity-90"
        >
          <span className="material-symbols-outlined text-[18px]">picture_as_pdf</span>
          Save as PDF
        </button>
      </div>

      <div className="report-sheet">
        {/* Brand header */}
        <header
          className="report-section"
          style={{
            display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start',
            borderBottom: '2px solid #17648d', paddingBottom: 14, marginBottom: 20,
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{
              width: 44, height: 44, borderRadius: 14,
              background: 'linear-gradient(135deg, #17648d, #76b6e3)',
              color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <span className="material-symbols-outlined" style={{ fontSize: 24 }}>child_care</span>
            </div>
            <div>
              <div style={{ fontSize: 20, fontWeight: 700, color: '#17648d', lineHeight: 1.15, fontFamily: 'Quicksand, sans-serif' }}>
                SmartCare Baby
              </div>
              <div style={{ fontSize: 10, color: '#576065', letterSpacing: 1.4, textTransform: 'uppercase', fontWeight: 700 }}>
                {title}
              </div>
            </div>
          </div>
          <div style={{ textAlign: 'right', fontSize: 11, color: '#576065', lineHeight: 1.6 }}>
            <div>Generated</div>
            <div style={{ fontWeight: 700, color: '#0b1c30', fontSize: 12 }}>{generatedOn}</div>
          </div>
        </header>

        {/* Page title block */}
        <div className="report-section" style={{ marginBottom: 20 }}>
          <h1 style={{ fontFamily: 'Quicksand, sans-serif', fontSize: 24, fontWeight: 700, margin: 0, color: '#0b1c30' }}>
            {title}
          </h1>
          {subtitle && (
            <p style={{ margin: '4px 0 0', fontSize: 12, color: '#576065' }}>{subtitle}</p>
          )}
        </div>

        {children}

        {/* Footer */}
        <footer
          style={{
            marginTop: 28, paddingTop: 12, borderTop: '1px solid #c0c7cf',
            fontSize: 10, color: '#576065', display: 'flex', justifyContent: 'space-between',
          }}
        >
          <span>SmartCare Baby · Safe Child Health Systems</span>
          <span>Page generated by SmartCare · Not a diagnostic document</span>
        </footer>
      </div>
    </div>
  );
}